[project]
name = "table-scrape-from-website"
version = "0.1.0"
description = "Table data extraction by Pandas and requests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
